import type { Metadata } from "next";
import "./globals.css";
import { Outfit, Ovo, Poppins } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],weight: ["400", "500", "600", "700"]
  // variable: "--font-outfit",
});

const ovo = Ovo({
  subsets: ["latin"],weight: ["400"]
  // variable: "--font-outfit",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Gamme Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`${outfit.className}  ${ovo.className} ${poppins.variable} antialiased leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
